type: geospatial

# Short text description of the data you are providing.
description: Incidents derived from SFPD Crime Incident Reporting system Updated daily, showing data from 1/1/2003 up until two weeks ago from current date. (https://data.sfgov.org/Public-Safety/SFPD-Incidents-from-1-January-2003/tmnf-yvry)

poweredBy: '<a href="https://data.sfgov.org/Public-Safety/SFPD-Incidents-from-1-January-2003/tmnf-yvry"><img src="http://www.socrata.com/wp-content/uploads/socrata-rectangle-color.png"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/Los_Angeles

soda:
- name: sfpd-incidents
  source: data.sfgov.org
  dataset: tmnf-yvry
  limit: 5000
  order: date DESC

# How often should River View poll your data sources?
interval: 5 days

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

fields:
- latitude
- longitude
- id
- category
- pddistrict
- pdid
- address
- descript
- resolution
