# Please name this the same as the directory it is in.
name: ercot
type: scalar

# Short text description of the data you are providing.
description: The Electric Reliability Council of Texas (ERCOT) manages scheduling on an electric grid carrying 85 percent of Texas' load.

poweredBy: '<a href="http://www.ercot.com"><img src="http://www.ercot.com/content/images/logos/logoBanner.gif"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/Chicago

# A list of URLs that contain the raw data. Each of these will be polled at the
# interval specified below, and the response text will be sent to your parser.
sources:
  - http://mis.ercot.com/misapp/GetReports.do?reportTypeId=12340&reportTitle=System-Wide%20Demand&showHTMLView=&mimicKey

# How often should River View poll your data sources?
interval: 1 hour

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

# Primary data, usually collected in one location. Should both be scalar values.
fields:
- Demand
