new: true

type: geospatial

# Short text description of the data you are providing.
description: All open graffiti removal requests made to 311 and all requests completed since January 1, 2011. The Department of Streets & Sanitation's Graffiti Blasters crews offer a vandalism removal service to private property owners. Graffiti Blasters employ "blast" trucks that use baking soda under high water pressure to erase painted graffiti from brick, stone and other mineral surfaces. They also use paint trucks to cover graffiti on the remaining surfaces. Organizations and residents may report graffiti and request its removal.

poweredBy: '<a href="https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Graffiti-Removal/hec5-y4x5"><img src="https://data.cityofchicago.org/stylesheets/images/domains/data.cityofchicago.org/chicago_logo.png"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/Chicago

soda:
- name: Graffiti Removal
  source: data.cityofchicago.org
  dataset: hec5-y4x5
  limit: 1000
  order: creation_date DESC
- name: Tree Trim
  source: data.cityofchicago.org
  dataset: uxic-zsuj
  limit: 600
  order: creation_date DESC
- name: Garbage Carts
  source: data.cityofchicago.org
  dataset: 9ksk-na4q
  limit: 400
  order: creation_date DESC
- name: Rodent Baiting
  source: data.cityofchicago.org
  dataset: 97t6-zrhs
  limit: 600
  order: creation_date DESC
- name: Tree Debris
  source: data.cityofchicago.org
  dataset: mab8-y9h3
  limit: 200
  order: creation_date DESC
- name: Abandoned Vehicles
  source: data.cityofchicago.org
  dataset: 3c9v-pnva
  limit: 200
  order: creation_date DESC
- name: Pot Holes
  source: data.cityofchicago.org
  dataset: 7as2-ds3y
  limit: 300
  order: creation_date DESC

# How often should River View poll your data sources?
interval: 1 day

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

fields:
- latitude
- longitude
- police_district
- zip_code
- status
- service_request_number
- ward
- community_area
- type_of_service_request
- street_address
